# cmux Cloud devbox agent config generator (/etc/cmux/agent-config.sh).
# Parity sources: web/services/vms/images/blaxel/agent-config.sh (byte-identical
# body below the header; vm-devbox-image.test.ts pins it) and chatmux
# infra/sandbox-images/agent-config.sh. Sourced from
# /etc/profile.d/cmux-agents.sh (login/exec shells) and the bashrc chain
# (interactive shells).
#
# Materializes per-harness model-proxy configs from the machine's boot env
# (OPENAI_BASE_URL / OPENAI_API_KEY / CMUX_CODEROUTER_URL, minted at VM
# create from the creator's coderouter team; see
# web/services/coderouter/vmModelPlane.ts). Idempotent and silent: each
# harness config is written only when missing, so a user who edits or
# deletes one keeps control.
#
# Create-time envs are not replayed on every provider (Blaxel resurrect;
# Freestyle has no VM-level create env at all), so shells that see the boot
# env persist it 0600 on disk, and shells that do not re-source the
# persisted copy. The persisted file always mirrors the newest boot env.

cmux_write_agent_configs() {
  if [ -n "${OPENAI_BASE_URL-}" ]; then
    mkdir -p "$HOME/.config/cmux" 2>/dev/null && (
      umask 077
      {
        echo "# generated by cmux from machine boot env; managed, do not edit"
        echo "export OPENAI_BASE_URL='$OPENAI_BASE_URL'"
        if [ -n "${OPENAI_API_KEY-}" ]; then
          echo "export OPENAI_API_KEY='$OPENAI_API_KEY'"
        fi
        if [ -n "${CMUX_CODEROUTER_URL-}" ]; then
          echo "export CMUX_CODEROUTER_URL='$CMUX_CODEROUTER_URL'"
        fi
      } > "$HOME/.config/cmux/model-plane.env" 2>/dev/null
    )
  elif [ -f "$HOME/.config/cmux/model-plane.env" ]; then
    . "$HOME/.config/cmux/model-plane.env" 2>/dev/null || true
  fi

  # codex: a CUSTOM provider, not the built-in openai one. A custom provider
  # defaults WebSockets OFF and pins the plain HTTP Responses API, which is
  # exactly what the /v1 data plane serves. Auth comes from OPENAI_API_KEY at
  # request time (env_key), so a rotated token needs no config rewrite.
  if [ -n "${OPENAI_BASE_URL-}" ] && [ ! -e "$HOME/.codex/config.toml" ]; then
    mkdir -p "$HOME/.codex" 2>/dev/null && {
      echo "# generated by cmux from machine boot env; delete to manage manually"
      echo "model_provider = \"cmux\""
      echo ""
      echo "[model_providers.cmux]"
      echo "name = \"cmux\""
      echo "base_url = \"$OPENAI_BASE_URL\""
      echo "env_key = \"OPENAI_API_KEY\""
      echo "wire_api = \"responses\""
      echo "requires_openai_auth = false"
      echo ""
      echo "[history]"
      echo "persistence = \"save-all\""
    } > "$HOME/.codex/config.toml" 2>/dev/null
  fi
}

cmux_write_agent_configs
unset -f cmux_write_agent_configs
