# cmux Cloud devbox agent config generator (/etc/cmux/agent-config.sh).
# Parity sources: the chatmux devbox agent-config (byte-identical
# body below the header; vm-devbox-image.test.ts pins it) and chatmux
# infra/sandbox-images/agent-config.sh. Sourced from
# /etc/profile.d/cmux-agents.sh (login/exec shells) and the bashrc chain
# (interactive shells).
#
# Materializes per-harness model-proxy configs from the machine's boot env
# (the model-plane vars listed in cmux_model_plane_vars, delivered at VM
# create; see web/services/coderouter/vmModelPlane.ts). The env carries
# base URLs, a public placeholder API key, and the VM id only: the real
# credential (the coderouter route token) is injected by the provider's TLS
# edge into every request the guest makes to the coderouter host, so no
# secret ever lands on the machine and no config below carries one.
# Idempotent and silent: each harness config is written only when missing,
# so a user who edits or deletes one keeps control.
#
# Create-time envs are not replayed on every provider (resurrect;
# Freestyle has no VM-level create env at all), so shells that see the boot
# env persist it 0600 on disk, and shells that do not re-source the
# persisted copy. The persisted file always mirrors the newest boot env.

# The edge terminates the coderouter session with the platform CA it
# installs at boot. curl, python, bun, and codex trust the system store;
# Node (Claude Code, pi) does not, so point it at the CA when present. A
# user-set NODE_EXTRA_CA_CERTS wins.
if [ -z "${NODE_EXTRA_CA_CERTS-}" ] && [ -f /usr/local/share/ca-certificates/freestyle-tls.crt ]; then
  NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/freestyle-tls.crt
  export NODE_EXTRA_CA_CERTS
fi

cmux_write_agent_configs() {
  # Every model-plane var, persisted generically; OPENAI_BASE_URL is the
  # anchor: its presence means a boot env is present.
  cmux_model_plane_vars="OPENAI_BASE_URL OPENAI_API_KEY CMUX_CODEROUTER_URL ANTHROPIC_BASE_URL ANTHROPIC_API_KEY CMUX_VM_ID"
  if [ -n "${OPENAI_BASE_URL-}" ]; then
    mkdir -p "$HOME/.config/cmux" 2>/dev/null && (
      umask 077
      {
        echo "# generated by cmux from machine boot env; managed, do not edit"
        for cmux_var in $cmux_model_plane_vars; do
          eval "cmux_val=\${$cmux_var-}"
          if [ -n "$cmux_val" ]; then
            printf "export %s='%s'\n" "$cmux_var" "$(printf '%s' "$cmux_val" | sed "s/'/'\\\\''/g")"
          fi
        done
      } > "$HOME/.config/cmux/model-plane.env" 2>/dev/null
    )
  elif [ -f "$HOME/.config/cmux/model-plane.env" ]; then
    . "$HOME/.config/cmux/model-plane.env" 2>/dev/null || true
  fi
  unset cmux_model_plane_vars cmux_var cmux_val

  # codex: a CUSTOM provider, not the built-in openai one. WebSockets are
  # gated per provider by supports_websockets (codex-rs
  # model_provider_info: serde default false; client.rs
  # responses_websocket_enabled checks nothing else), so a custom provider
  # is already HTTP-only. It is pinned false explicitly anyway: the /v1 data
  # plane serves only the plain HTTP Responses API, and an implicit default
  # can move under a codex upgrade. Auth comes from OPENAI_API_KEY at request
  # time (env_key); it is the public placeholder, and the edge adds the real
  # credential, so a rotated token needs no config rewrite.
  if [ -n "${OPENAI_BASE_URL-}" ] && [ ! -e "$HOME/.codex/config.toml" ]; then
    mkdir -p "$HOME/.codex" 2>/dev/null && {
      echo "# generated by cmux from machine boot env; delete to manage manually"
      echo "model_provider = \"cmux\""
      echo ""
      echo "[model_providers.cmux]"
      echo "name = \"cmux\""
      echo "base_url = \"$OPENAI_BASE_URL\""
      echo "env_key = \"OPENAI_API_KEY\""
      echo "wire_api = \"responses\""
      echo "requires_openai_auth = false"
      echo "supports_websockets = false"
      echo ""
      echo "[history]"
      echo "persistence = \"save-all\""
    } > "$HOME/.codex/config.toml" 2>/dev/null
  fi

  # pi: override the built-in openai-codex provider, whose
  # openai-codex-responses implementation speaks the exact dialect the /v1
  # plane proxies (it appends /codex/responses to baseUrl, which the plane
  # serves). pi derives a chatgpt-account-id header from its apiKey
  # client-side and refuses a non-JWT, so the apiKey carries the same public
  # placeholder JWT the `cr pi` extension ships. No route-token header is
  # configured: the edge supplies it on every request. baseUrl must be a
  # literal (pi does not env-resolve it), hence this generator.
  if [ -n "${OPENAI_BASE_URL-}" ] && [ ! -e "$HOME/.pi/agent/models.json" ]; then
    mkdir -p "$HOME/.pi/agent" 2>/dev/null && {
      echo '{'
      echo '  "providers": {'
      echo '    "openai-codex": {'
      echo '      "name": "cmux",'
      echo "      \"baseUrl\": \"$OPENAI_BASE_URL\","
      echo '      "apiKey": "e30.eyJodHRwczovL2FwaS5vcGVuYWkuY29tL2F1dGgiOnsiY2hhdGdwdF9hY2NvdW50X2lkIjoiY29kZXJvdXRlciJ9fQ.signature"'
      echo '    }'
      echo '  }'
      echo '}'
    } > "$HOME/.pi/agent/models.json" 2>/dev/null
  fi

  # claude: ANTHROPIC_BASE_URL and the placeholder ANTHROPIC_API_KEY in the
  # env are all Claude Code needs; nothing is written.

  # opencode: the provider catalog (ids, npm packages, model lists) lives in
  # the team's opencode console account behind the coderouter proxy and
  # changes without image rebuilds, so the ready-made rewritten config is
  # fetched from the coderouter opencode config endpoint instead of being
  # guessed statically. The endpoint inlines each provider's apiKey; it is
  # swapped for an {env:OPENAI_API_KEY} reference that opencode resolves at
  # request time, and any route-token-shaped value is swapped the same way so
  # a token never lands on disk. A coderouter outage, a team without an
  # opencode account (503), or an empty catalog writes nothing and the next
  # shell retries.
  if [ -n "${CMUX_CODEROUTER_URL-}" ] && [ -n "${OPENAI_API_KEY-}" ] \
    && [ ! -e "$HOME/.config/opencode/opencode.json" ] \
    && command -v curl >/dev/null 2>&1; then
    cmux_opencode_config=$(curl -fsS --connect-timeout 2 -m 10 \
      -H "authorization: Bearer $OPENAI_API_KEY" \
      "$CMUX_CODEROUTER_URL/api/coderouter/opencode/config" 2>/dev/null) || cmux_opencode_config=""
    case $cmux_opencode_config in
      '{"provider":{}}') ;;
      '{"provider":'*)
        mkdir -p "$HOME/.config/opencode" 2>/dev/null && (
          umask 077
          printf '%s\n' "$cmux_opencode_config" \
            | sed "s/\"$OPENAI_API_KEY\"/\"{env:OPENAI_API_KEY}\"/g" \
            | sed 's/"crt_[A-Za-z0-9._-]*"/"{env:OPENAI_API_KEY}"/g' \
            > "$HOME/.config/opencode/opencode.json"
        ) 2>/dev/null
        ;;
    esac
    unset cmux_opencode_config
  fi
}

cmux_write_agent_configs
unset -f cmux_write_agent_configs
