@preconcurrency import Foundation
import CryptoKit
import OSLog

/// Finds a cmux-owned headless-shell executable and optionally installs one.
/// The Foundation file manager is thread-safe; keeping it private prevents
/// callers from mutating the store's file-system dependency after creation.
/// SAFETY: the immutable `FileManager`, `URLSession`, storage resolver, and
/// `@Sendable` providers are only used through Foundation's thread-safe APIs.
struct ChromiumRuntimeArtifactStore: Sendable {
    // URLSession's resource timeout is caller-configurable; this outer
    // deadline also bounds sessions supplied by tests or the app composition.
    private let downloadTimeout: Duration

    // FileManager is documented thread-safe. Keep the escape hatch on the
    // single immutable property used by filesystem operations.
    private nonisolated(unsafe) let fileManager: FileManager
    private let urlSession: URLSession
    private let storage: ChromiumOwnedStorage
    let executableOverrideProvider: @Sendable () -> URL?

    init(
        fileManager: FileManager,
        urlSession: URLSession,
        executableOverrideProvider: @escaping @Sendable () -> URL?,
        storage: ChromiumOwnedStorage,
        downloadTimeout: Duration = .seconds(120)
    ) {
        self.downloadTimeout = downloadTimeout
        self.fileManager = fileManager
        self.urlSession = urlSession
        self.storage = storage
        self.executableOverrideProvider = executableOverrideProvider
    }

    func installedExecutable(
        manifest: ChromiumRuntimeManifest = .production
    ) -> URL? {
        if let override = executableOverrideProvider(), fileManager.isExecutableFile(atPath: override.path) {
            return override
        }
        guard let artifact = manifest.artifact() else { return nil }
        return installedExecutable(for: artifact)
    }

    /// Returns an installed executable, downloading the pinned production
    /// artifact when this is the first Chromium pane on the machine.
    ///
    /// An explicit `CMUX_CHROMIUM_EXECUTABLE` override is intended for local
    /// development and tests. It is still validated as an executable and is
    /// never used as a profile directory.
    func ensureInstalled(
        manifest: ChromiumRuntimeManifest = .production
    ) async throws -> URL {
        if let executable = installedExecutable(manifest: manifest) {
            return executable
        }
        guard let artifact = manifest.artifact() else {
            throw ChromiumRuntimeArtifactError.unsupportedPlatform
        }
        return try await install(artifact)
    }

    /// Installs an archive into the cmux-owned runtime directory. The caller
    /// supplies a pinned descriptor (normally generated by the build/release
    /// manifest), so an arbitrary URL cannot be introduced by page content.
    func install(_ artifact: ChromiumRuntimeArtifact) async throws -> URL {
        let root: URL
        do {
            root = try storage.runtimeDirectory()
        } catch {
            throw ChromiumRuntimeArtifactError.executableNotFound
        }
        let download = try await withThrowingTaskGroup(of: ChromiumRuntimeDownloadResult.self) { group in
            group.addTask {
                let (archiveURL, response) = try await urlSession.download(from: artifact.downloadURL)
                return ChromiumRuntimeDownloadResult(archiveURL: archiveURL, response: response)
            }
            group.addTask { [downloadTimeout] in
                // A CDN stall is a genuine operation deadline, not a state
                // polling delay; cancellation stops the URLSession task.
                try await ContinuousClock().sleep(for: downloadTimeout)
                throw ChromiumRuntimeArtifactError.downloadFailed("timeout")
            }
            defer { group.cancelAll() }
            guard let result = try await group.next() else {
                throw CancellationError()
            }
            return result
        }
        let archiveURL = download.archiveURL
        let response = download.response
        guard let httpResponse = response as? HTTPURLResponse,
              (200...299).contains(httpResponse.statusCode) else {
            let status = (response as? HTTPURLResponse)?.statusCode ?? -1
            throw ChromiumRuntimeArtifactError.downloadFailed("HTTP \(status)")
        }
        if let expected = artifact.sha256?.lowercased(), !expected.isEmpty {
            let actual = Self.sha256(for: archiveURL)
            guard actual == expected else {
                throw ChromiumRuntimeArtifactError.checksumMismatch(expected: expected, actual: actual)
            }
        }

        let staging = root.appendingPathComponent(".staging-\(UUID().uuidString)", isDirectory: true)
        try fileManager.createDirectory(at: staging, withIntermediateDirectories: true)
        defer { try? fileManager.removeItem(at: staging) }
        try await validateArchiveEntries(archiveURL, staging: staging)
        try await extractArchive(archiveURL, into: staging)
        try Self.validateExtractedTree(staging, fileManager: fileManager)
        let executable = try Self.findExecutable(in: staging, fileManager: fileManager)
        guard let extractedRoot = Self.archiveRoot(containing: executable, under: staging) else {
            throw ChromiumRuntimeArtifactError.invalidArchive
        }

        // Install the complete extracted directory, not just the executable:
        // headless-shell loads its resource packs and dynamic libraries next
        // to the binary. A version/platform directory permits a future pinned
        // revision to coexist while an old pane is still shutting down.
        let installDirectory = root
            .appendingPathComponent(artifact.version, isDirectory: true)
            .appendingPathComponent(artifact.platform, isDirectory: true)
        try fileManager.createDirectory(
            at: installDirectory.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )

        // Copy into a unique sibling and move the completed tree into place.
        // A pane can start while another pane is performing the first-run
        // download; an atomic directory move prevents either process from
        // observing or deleting a partially-installed runtime.
        let installStaging = installDirectory
            .deletingLastPathComponent()
            .appendingPathComponent(".install-\(UUID().uuidString)", isDirectory: true)
        defer { try? fileManager.removeItem(at: installStaging) }
        if extractedRoot.standardizedFileURL.path == staging.standardizedFileURL.path {
            try? fileManager.removeItem(at: staging.appendingPathComponent(".archive-entries"))
        }
        try fileManager.moveItem(at: extractedRoot, to: installStaging)
        let relativeExecutablePath = executable.path
            .replacingOccurrences(of: extractedRoot.path + "/", with: "")
        if fileManager.fileExists(atPath: installDirectory.path) {
            if let existing = try? Self.findExecutable(in: installDirectory, fileManager: fileManager) {
                return existing
            }
            // Preserve an interrupted/incomplete tree instead of deleting a
            // path another process might still be inspecting. Renaming a
            // directory on one volume is atomic, so the destination is either
            // the old complete tree or absent while the finished staging tree
            // is moved into place below.
            let quarantine = installDirectory
                .deletingLastPathComponent()
                .appendingPathComponent(".incomplete-\(UUID().uuidString)", isDirectory: true)
            do {
                try fileManager.moveItem(at: installDirectory, to: quarantine)
            } catch {
                if let existing = try? Self.findExecutable(in: installDirectory, fileManager: fileManager) {
                    return existing
                }
                throw ChromiumRuntimeArtifactError.extractionFailed("quarantine failed")
            }
        }
        do {
            try fileManager.moveItem(at: installStaging, to: installDirectory)
        } catch {
            // Another installer may have won the race between the existence
            // check and the move. Prefer its verified executable over failing
            // a second Chromium pane.
            if let existing = installedExecutable(for: artifact) {
                return existing
            }
            throw ChromiumRuntimeArtifactError.extractionFailed("install failed")
        }
        let installedExecutable = installDirectory.appendingPathComponent(
            relativeExecutablePath,
            isDirectory: false
        )
        guard fileManager.isExecutableFile(atPath: installedExecutable.path) else {
            throw ChromiumRuntimeArtifactError.executableNotFound
        }
        return installedExecutable
    }

    /// Finds only the runtime revision and architecture described by the
    /// selected artifact. Older revisions may coexist for already-running
    /// panes, but a new pane must never launch one by accident.
    private func installedExecutable(for artifact: ChromiumRuntimeArtifact) -> URL? {
        guard let root = try? storage.runtimeDirectory() else { return nil }
        let installDirectory = root
            .appendingPathComponent(artifact.version, isDirectory: true)
            .appendingPathComponent(artifact.platform, isDirectory: true)
        return try? Self.findExecutable(in: installDirectory, fileManager: fileManager)
    }

    /// Runs the system archive tool without blocking an executor thread on
    /// `waitUntilExit()`. The termination callback is the process readiness
    /// signal; stderr is drained after termination because `unzip -q` emits
    /// only bounded diagnostics. Raw diagnostics are retained for private
    /// logging and never become part of the user-facing error.
    private func extractArchive(_ archiveURL: URL, into staging: URL) async throws {
        let unzip = Process()
        unzip.executableURL = URL(fileURLWithPath: "/usr/bin/unzip")
        unzip.arguments = ["-q", archiveURL.path, "-d", staging.path]
        let errorPipe = Pipe()
        unzip.standardError = errorPipe
        unzip.standardOutput = FileHandle.nullDevice

        let status: Int32
        do {
            status = try await runProcess(unzip)
        } catch {
            throw ChromiumRuntimeArtifactError.extractionFailed("unzip could not start")
        }
        let diagnostics = String(
            data: errorPipe.fileHandleForReading.readDataToEndOfFile(),
            encoding: .utf8
        )?.trimmingCharacters(in: .whitespacesAndNewlines)
        if status != 0 {
            if let diagnostics, !diagnostics.isEmpty {
                Logger(subsystem: "com.cmux.browser", category: "runtime")
                    .error("Chromium archive extraction failed: \(diagnostics, privacy: .private(mask: .hash))")
            }
            throw ChromiumRuntimeArtifactError.extractionFailed("unzip failed")
        }
    }

    /// Lists archive members before extraction and rejects path traversal. The
    /// listing is written to a staging file rather than an in-memory pipe so a
    /// malformed archive cannot back-pressure the child process while cmux is
    /// waiting for its termination signal.
    private func validateArchiveEntries(_ archiveURL: URL, staging: URL) async throws {
        let listingURL = staging.appendingPathComponent(".archive-entries", isDirectory: false)
        guard fileManager.createFile(atPath: listingURL.path, contents: nil) else {
            throw ChromiumRuntimeArtifactError.invalidArchive
        }
        let listingHandle: FileHandle
        do {
            listingHandle = try FileHandle(forWritingTo: listingURL)
        } catch {
            throw ChromiumRuntimeArtifactError.invalidArchive
        }
        defer { try? listingHandle.close() }

        let listing = Process()
        listing.executableURL = URL(fileURLWithPath: "/usr/bin/unzip")
        listing.arguments = ["-Z1", archiveURL.path]
        listing.standardOutput = listingHandle
        listing.standardError = FileHandle.nullDevice
        let status: Int32
        do {
            status = try await runProcess(listing)
        } catch {
            throw ChromiumRuntimeArtifactError.invalidArchive
        }
        guard status == 0 else {
            throw ChromiumRuntimeArtifactError.invalidArchive
        }

        try listingHandle.close()
        guard let data = try? Data(contentsOf: listingURL),
              let text = String(data: data, encoding: .utf8),
              !data.contains(0) else {
            throw ChromiumRuntimeArtifactError.invalidArchive
        }

        let stagingRoot = staging.standardizedFileURL.path
        for rawEntry in text.split(separator: "\n", omittingEmptySubsequences: true) {
            let entry = String(rawEntry).trimmingCharacters(in: CharacterSet(charactersIn: "\r"))
            guard !entry.isEmpty,
                  !entry.hasPrefix("/"),
                  !entry.hasPrefix("\\"),
                  !entry.contains("\\") else {
                throw ChromiumRuntimeArtifactError.invalidArchive
            }
            let components = entry.split(separator: "/", omittingEmptySubsequences: false)
            guard !components.contains(where: { $0 == ".." || $0.contains("\0") }) else {
                throw ChromiumRuntimeArtifactError.invalidArchive
            }
            let destination = staging.appendingPathComponent(entry).standardizedFileURL.path
            guard destination == stagingRoot || destination.hasPrefix(stagingRoot + "/") else {
                throw ChromiumRuntimeArtifactError.invalidArchive
            }
        }
    }

    /// `unzip` can represent symbolic links in an archive. The Chrome for
    /// Testing app bundle relies on the standard macOS framework layout
    /// (`Versions/Current` and friends), so symlinks are allowed — but only
    /// when they resolve inside the staging directory. A link escaping the
    /// tree would let a later resource lookup traverse outside the managed
    /// runtime, so it still rejects the archive.
    private static func validateExtractedTree(
        _ staging: URL,
        fileManager: FileManager
    ) throws {
        let root = staging.standardizedFileURL.resolvingSymlinksInPath().path
        let enumerator = fileManager.enumerator(
            at: staging,
            includingPropertiesForKeys: [.isSymbolicLinkKey]
        )
        while let candidate = enumerator?.nextObject() as? URL {
            let candidatePath = candidate.standardizedFileURL.path
            guard candidatePath == root || candidatePath.hasPrefix(root + "/") else {
                throw ChromiumRuntimeArtifactError.invalidArchive
            }
            let values = try candidate.resourceValues(forKeys: [.isSymbolicLinkKey])
            if values.isSymbolicLink == true {
                let destination = try fileManager.destinationOfSymbolicLink(atPath: candidate.path)
                guard !destination.hasPrefix("/") else {
                    throw ChromiumRuntimeArtifactError.invalidArchive
                }
            }
            let resolvedPath = candidate.resolvingSymlinksInPath().standardizedFileURL.path
            guard resolvedPath == root || resolvedPath.hasPrefix(root + "/") else {
                throw ChromiumRuntimeArtifactError.invalidArchive
            }
        }
    }

    private func runProcess(_ process: Process) async throws -> Int32 {
        try await withCheckedThrowingContinuation { (continuation: CheckedContinuation<Int32, any Error>) in
            let completion = ChromiumExtractionCompletion()
            process.terminationHandler = { process in
                guard completion.claim() else { return }
                continuation.resume(returning: process.terminationStatus)
            }
            do {
                try process.run()
            } catch {
                guard completion.claim() else { return }
                continuation.resume(throwing: error)
            }
        }
    }

    /// Executable names accepted inside a pinned runtime tree: the full
    /// Chrome for Testing app-bundle binary, plus the plain `chrome` binary
    /// used by flat layouts. `chrome-headless-shell` is deliberately absent:
    /// an install left behind by a pre-extension build shares the same
    /// version/platform directory, and refusing to find it here routes the
    /// next launch through `install(_:)`, which quarantines the stale tree
    /// and downloads the pinned full browser.
    private static let executableNames: Set<String> = [
        "Google Chrome for Testing",
        "chrome",
    ]

    private static func findExecutable(in root: URL, fileManager: FileManager) throws -> URL {
        if Self.executableNames.contains(root.lastPathComponent),
           fileManager.isExecutableFile(atPath: root.path) {
            return root
        }
        let enumerator = fileManager.enumerator(at: root, includingPropertiesForKeys: [.isRegularFileKey])
        while let candidate = enumerator?.nextObject() as? URL {
            guard Self.executableNames.contains(candidate.lastPathComponent),
                  fileManager.isExecutableFile(atPath: candidate.path) else { continue }
            // The app bundle contains identically-prefixed helper binaries;
            // only the browser binary lives directly under `Contents/MacOS`
            // of the outer bundle or stands alone at the tree root.
            if candidate.lastPathComponent == "Google Chrome for Testing" {
                let parents = candidate.pathComponents.dropLast()
                guard parents.suffix(2).elementsEqual(["Contents", "MacOS"]) else { continue }
            }
            return candidate
        }
        throw ChromiumRuntimeArtifactError.executableNotFound
    }

    private static func archiveRoot(containing executable: URL, under staging: URL) -> URL? {
        let normalizedExecutable = executable.standardizedFileURL
        let normalizedStaging = staging.standardizedFileURL
        guard normalizedExecutable.path == normalizedStaging.path
                || normalizedExecutable.path.hasPrefix(normalizedStaging.path + "/") else {
            return nil
        }
        let relative = normalizedExecutable.path
            .replacingOccurrences(of: normalizedStaging.path, with: "")
            .trimmingCharacters(in: CharacterSet(charactersIn: "/"))
        guard !relative.isEmpty else { return nil }
        guard normalizedExecutable.deletingLastPathComponent() != normalizedStaging else {
            return normalizedStaging
        }
        guard let firstComponent = relative.split(separator: "/").first,
              !firstComponent.isEmpty else {
            return nil
        }
        return normalizedStaging.appendingPathComponent(String(firstComponent), isDirectory: true)
    }

    private static func sha256(for url: URL) -> String {
        guard let bytes = try? Data(contentsOf: url, options: [.mappedIfSafe]) else { return "" }
        return SHA256.hash(data: bytes)
            .map { String($0, radix: 16).leftPadded(toLength: 2, with: "0") }
            .joined()
    }
}

private extension String {
    func leftPadded(toLength length: Int, with character: Character) -> String {
        guard count < length else { return self }
        return String(repeating: character, count: length - count) + self
    }
}
