#!/usr/bin/env python3
"""Generate the embedded cmux.json schema used by the native CLI validator."""

from __future__ import annotations

import argparse
import base64
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = Path("web") / "data" / "cmux.schema.json"
OUTPUT_PATH = (
    Path("Packages")
    / "macOS"
    / "CmuxFoundation"
    / "Sources"
    / "CmuxFoundation"
    / "ConfigValidation"
    / "CmuxConfigSchema.generated.swift"
)
SCHEMA = ROOT / SCHEMA_PATH
OUTPUT = ROOT / OUTPUT_PATH


def generated_source(schema: Path = SCHEMA) -> str:
    encoded = base64.b64encode(schema.read_bytes()).decode("ascii")
    chunks = [encoded[i : i + 400] for i in range(0, len(encoded), 400)]
    body = "\n".join(f'        "{chunk}",' for chunk in chunks)
    return f"""// Generated by scripts/generate-cmux-config-schema.py. Do not edit.
// Source: web/data/cmux.schema.json

import Foundation

enum CmuxEmbeddedConfigSchema {{
    static let data: Data = {{
        let base64 = [
{body}
        ].joined()
        guard let data = Data(base64Encoded: base64) else {{
            preconditionFailure("embedded cmux.json schema is corrupt")
        }}
        return data
    }}()
}}
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    # Read the schema from, and write the Swift into, another checkout. PR
    # catch-up runs this trusted copy against a pull request's tree
    # (scripts/ci/catch_up_pr.py), so the generator never comes from that tree.
    parser.add_argument("--root", type=Path, default=ROOT)
    args = parser.parse_args()
    root = args.root.resolve()
    output = root / OUTPUT_PATH
    expected = generated_source(root / SCHEMA_PATH)
    if args.check:
        if not output.exists() or output.read_text() != expected:
            print(f"{OUTPUT_PATH} is stale; run {Path(__file__).name}")
            return 1
        return 0
    output.write_text(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
